version: '3'

services:
  mongo:
    container_name: 'shortener_mongo'
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  server:
    container_name: "pathways_server"
    build: .
    env_file: .env
    ports:
      - 3003:3000
    expose:
      - 3000
    volumes:
      - ./:/home/node/app
    depends_on:
      - mongo


volumes:
  mongodb_data_container:
